namespace: lucheon
name: hypervisor
version: 1.0.0
readme: README.md
authors:
- Etienne Barbier <etienne.barbier1@grenoble-inp.org>
description: Collection with hypervisor stuff
license:
- GPL-2.0-or-later
tags: []
dependencies: {}
repository: https://github.com/Lucheon/ansible-hypervisor
